version: "2.3"

networks:
  ros:
    driver: bridge

services:
  ros-master:
    image: osrf/ros:noetic-desktop-full
    command: roscore
    networks:
      - ros
    restart: always

  dummy_camera:
    image: shiotani_stereo:latest
    command: bash /root/catkin_ws/src/dummy_camera/src/dummy_camera.sh
    depends_on:
      - ros-master
    networks:
      - ros
    environment: 
      - "ROS_MASTER_URI=http://ros-master:11311"
      - "ROS_HOSTNAME=dummy_camera"

  stereo_matching:
    image: shiotani_stereo:latest
    command: python /root/catkin_ws/src/stereo_matching/src/stereo_matching.py
    depends_on:
      - ros-master
    networks:
      - ros
    runtime: nvidia
    environment: 
      - NVIDIA_VISIBLE_DEVICES=0,1
      - NVIDIA_DRIVER_CAPABILITIES=utility,compute
      - "ROS_MASTER_URI=http://ros-master:11311"
      - "ROS_HOSTNAME=stereo_matching"
#    command: bash -c "rosbag play -l /root/catkin_ws/src/dummy_camera/2021-05-20-09-24-08.bag &&
#                      python /root/catkin_ws/src/dummy_camera/src/dummy_camera.py &&
#                      python /root/catkin_ws/src/stereo_matching/src/stereo_matching.py"
#    restart: always





