version: "2.3"

networks:
  ros:
    driver: bridge

services:
  ros-master:
    image: osrf/ros:noetic-desktop-full
    command: roscore
    networks:
      - ros
    restart: always

  dummy_camera:
    image: shiotani_stereo:latest
    command: bash /root/catkin_ws/src/dummy_camera/src/dummy_camera.sh
    depends_on:
      - ros-master
    networks:
      - ros
    environment: 
      - "ROS_MASTER_URI=http://ros-master:11311"
      - "ROS_HOSTNAME=dummy_camera"

  stereo_matching:
    image: shiotani_stereo:latest
    command: python /root/catkin_ws/src/stereo_matching/src/stereo_matching.py
#    command: python /root/keep_alive.py
    depends_on:
      - ros-master
    networks:
      - ros
    runtime: nvidia
    environment: 
      - NVIDIA_VISIBLE_DEVICES=6
      - NVIDIA_DRIVER_CAPABILITIES=utility,compute
      - "ROS_MASTER_URI=http://ros-master:11311"
      - "ROS_HOSTNAME=stereo_matching"

  instance_segmentation:
    image: shiotani_instance:latest
    command: bash -c "source ~/catkin_ws/devel/setup.bash && cd /root/catkin_ws/src/instance_segmentation/src/ && python instance_segmentation_node.py"
#    command: python /root/keep_alive.py
    depends_on:
      - ros-master
    networks:
      - ros
    runtime: nvidia
    environment: 
      - NVIDIA_VISIBLE_DEVICES=7
      - NVIDIA_DRIVER_CAPABILITIES=utility,compute
      - "ROS_MASTER_URI=http://ros-master:11311"
      - "ROS_HOSTNAME=instance_segmentation"

  synthesis:
    image: shiotani_synthesis:latest
#    command: bash -c "source ~/catkin_ws/devel/setup.bash && cd /root/catkin_ws/src/instance_segmentation/src/ && python instance_segmentation_node.py"
    command: python /root/keep_alive.py
    depends_on:
      - ros-master
    networks:
      - ros
    environment: 
      - "ROS_MASTER_URI=http://ros-master:11311"
      - "ROS_HOSTNAME=synthesis"
