version: "2.3"

networks:
  ros:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16
          gateway: 172.21.0.1

services:
  dummy_camera:
    image: shiotani_stereo:latest
    command: bash /root/catkin_ws/src/dummy_camera/src/dummy_camera.sh
    networks:
      ros:
        ipv4_address: 172.21.0.2
    environment: 
      - "ROS_MASTER_URI=http://10.9.14.101:11311"
      - "ROS_HOSTNAME=172.21.0.2"

  stereo_matching:
    image: shiotani_stereo:latest
    command: bash -c "source ~/catkin_ws/devel/setup.bash && cd ~/catkin_ws/src/stereo_matching/src/ && python stereo_matching_image.py"
#    command: python /root/keep_alive.py
    networks:
      ros:
        ipv4_address: 172.21.0.3
    runtime: nvidia
    environment: 
      - "ROS_MASTER_URI=http://10.9.14.101:11311"
      - "ROS_HOSTNAME=172.21.0.3"
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=utility,compute

  instance_segmentation:
    image: shiotani_instance:latest
#    command: bash -c "source ~/catkin_ws/devel/setup.bash && cd /root/catkin_ws/src/instance_segmentation/src/ && python instance_segmentation_node.py"
    command: python /root/keep_alive.py
    networks:
      ros:
        ipv4_address: 172.21.0.4
    runtime: nvidia
    environment: 
      - "ROS_MASTER_URI=http://10.9.14.101:11311"
      - "ROS_HOSTNAME=172.21.0.4"
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=utility,compute

  synthesis:
    image: shiotani_synthesis:latest
    command: bash -c "source ~/catkin_ws/devel/setup.bash && cd /root/catkin_ws/src/synthesis/src/ && python synthesis_node_vector.py"
#    command: python /root/keep_alive.py
    networks:
      ros:
        ipv4_address: 172.21.0.5
    environment: 
      - "ROS_MASTER_URI=http://10.9.14.101:11311"
      - "ROS_HOSTNAME=172.21.0.5"
